Repository fusionjs/fusion-core, pull requests merged in 2018-11, with the labels that each got.

#335 Fix aliasing with optional tokens
  src/__tests__/dependency-resolution.js
  src/base-app.js
Labels: bugfix

#336 Release v1.9.1-0
  package.json
Labels: release

#337 Disable flow temporarily for failing 0.85 upgrade
  package.json
  src/plugins/ssr.js
  src/plugins/timing.js
  src/tokens.js
  yarn.lock
Labels: dependencies, greenkeeping

#341 Release v1.10.0
  package.json
Labels: release

#343 Upgrade dependencies
  flow-typed/npm/koa_v2.x.x.js
  package.json
  src/__tests__/index.node.js
  src/__tests__/sanitization.node.js
  src/flow/flow-fixtures.js
  src/tokens.js
  yarn.lock
Labels: greenkeeping

#345 Remove fusion-cli peer dep
  package.json
Labels: bugfix
