Repository fusionjs/fusion-core, pull requests merged in 2018-08, with the labels that each got.

#257 Change script order, add fusion-cli peer dependency
  package.json
  src/plugins/ssr.js
Labels: dependencies

#258 Release v1.5.0-beta.0
  package.json
Labels: release

#261 Fix typo in README.md
  README.md
Labels: docs

#269 Add CSP nonces to chuck script tags
  src/plugins/ssr.js
Labels: bugfix

#271 Release v1.5.1-0
  package.json
Labels: release

#273 Delete vestigial chunk preloading code
  package.json
  src/plugins/ssr.js
Labels: dependencies, greenkeeping
