Repository fusionjs/fusion-core, pull requests merged in 2018-09, with the labels that each got.

#282 Release v1.5.1
  package.json
Labels: release

#286 Provide additional ctx for RenderToken
  src/plugins/client-renderer.js
  src/plugins/server-renderer.js
Labels: feature

#283 Apply type casting in createToken to avoid $FlowFixMe
  src/create-token.js
Labels: bugfix

#287 Ensure that chunks are unique and filter out duplicate preload chunks
  src/plugins/ssr.js
Labels: bugfix

#288 Release v1.5.2
  package.json
Labels: release

#292 Release v1.5.3-0
  package.json
Labels: release

#291 Move SSR body template into DI system
  src/base-app.js
  src/plugins/ssr.js
  src/server-app.js
  src/tokens.js
  src/types.js
Labels: feature

#300 Release v1.6.1
  package.json
Labels: release

#301 Release v1.7.0-alpha.0
  package.json
Labels: release

#302 Release v1.7.0-alpha.1
  package.json
Labels: release

#303 Release v1.7.0-alpha.2
  package.json
Labels: release

#304 Release v1.7.0-alpha.3
  package.json
Labels: release

#305 Release v1.7.0-alpha.4
  package.json
Labels: release

#290 Expose resolved services as a private API
  src/__tests__/app-interface.js
  src/__tests__/dependency-resolution.js
  src/base-app.js
  src/base-app.js.flow
Labels: feature

#297 Refactor extraneous registration logic to support plugins that are re-registered
  src/__tests__/dependency-resolution.js
  src/__tests__/enhance.js
  src/base-app.js
Labels: feature

#306 Release v1.7.0-0
  package.json
Labels: release

#307 Release v1.7.0-alpha.5
  package.json
Labels: release

#308 Release v1.7.0-alpha.6
  package.json
Labels: release

#309 Make SSRBodyTemplate optional, export RoutePrefixToken and CriticalChunkIdsToken
  src/base-app.js
  src/index.js
  src/plugins/ssr.js
  src/server-app.js
  src/tokens.js
Labels: feature

#310 Release v1.7.0-1
  package.json
Labels: release
