Repository fusionjs/fusion-core, pull requests merged in 2018-10, with the labels that each got.

#313 Add CSP nonce to preload link tags
  src/plugins/ssr.js
Labels: bugfix

#314 Fix double fetching resulting from preload hint cache miss if using CDN
  src/plugins/ssr.js
Labels: bugfix

#315 Release v1.7.0-2
  package.json
Labels: release

#316 Release v1.7.0
  package.json
Labels: release

#318 Upgrade dependency versions
  package.json
  yarn.lock
Labels: greenkeeping

#320 Add bot whitelist
  src/__tests__/index.node.js
  src/plugins/ssr.js
Labels: bugfix

#322 Make missing token error more actionable
  src/__tests__/enhance.js
  src/base-app.js
  src/create-token.js
  src/types.js
Labels: feature

#325 Freeze TokenType enum map for Flow
  src/create-token.js
Labels: bugfix

#327 Enable proxy by default
  src/__tests__/index.node.js
  src/server-app.js
Labels: bugfix

#328 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor

#331 Allow orphan plugins when registered with a plugin enhancer
  src/__tests__/enhance.js
  src/base-app.js
Labels: bugfix

#332 Release v1.9.0-0
  package.json
Labels: release

#333 Resolve timing.end on errored requests
  src/__tests__/timing.js
  src/plugins/timing.js
Labels: bugfix

#334 Release v1.9.0
  package.json
Labels: release
