Repository fusionjs/fusion-core, pull requests merged in 2019-03, with the labels that each got.

#360 Export workerUrl virtual method
  src/__tests__/exports.js
  src/__tests__/virtual.js
  src/index.js
  src/virtual/index.js
Labels: bugfix

#362 Release v1.10.4-2
  package.json
Labels: release

#364 Upgrade flow-bin dependency to v0.94.0
  package.json
  yarn.lock
Labels: greenkeeping

#365 Release v1.10.4
  package.json
Labels: release

#367 Release v1.10.5-debugging
  package.json
Labels: release

#370 Release v1.10.5-debugging-2
  package.json
Labels: release

#371 Fix SSR Decider for Bots
  src/__tests__/app.node.js
  src/__tests__/index.node.js
  src/__tests__/test-helper.js
  src/plugins/ssr.js
Labels: bugfix

#372 Release v1.10.5
  package.json
Labels: release

#373 Include svg and js.map in the extension list determining SSR
  src/__tests__/index.node.js
  src/plugins/ssr.js
Labels: bugfix

#374 Release v1.10.6
  package.json
Labels: release
