Repository fusionjs/fusion-core, pull requests merged in 2019-02, with the labels that each got.

#356 Upgrade flow-bin to latest and fixes
  package.json
  src/__tests__/sanitization.node.js
  yarn.lock
Labels: bugfix

#357 Release v1.10.3
  package.json
Labels: release

#358 Upgrade flow to 0.93.0
  .eslintignore
  flow-typed/npm/koa_v2.x.x.js
  package.json
  yarn.lock
Labels: greenkeeping

#359 Release v1.10.4-0
  package.json
Labels: release
